name: "Terraform CI"

on:
  push:
    branches:
      - main
    paths:
      - 'website/**' # Trigger only for changes in the frontend directory

jobs:
  deploy-frontend-code:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Upload files to S3
    - name: Upload files to S3
      run: |
        aws s3 sync ./website s3://$AWS_S3_BUCKET --exclude ".DS_Store" --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.S3_REGION }}
